Clcheles MRTK3 Tutorial
microsoft/MRTK3-iet-tutorials pull request #34
Opened 2023-07-24 16:58 UTC by cheles

Upgrade to 2021.3.28f1 / link fixes / TutorialCallbacks  methods to ignoreCase

2023-07-26 18:06 UTC, AMollis requested changes

2023-07-26 18:14 UTC, cheles commented on Packages/manifest.json
>      "com.microsoft.mrtk.uxcore": "file:MixedReality/com.microsoft.mrtk.uxcore-3.0.0-pre.11.tgz",
I kept this file more for Unity 2021.3.11f1 to 28f1 upgrade, but didn't tested with latest MRTK3 prev17. I can test tomorrow and repush if needed.

2023-07-26 22:56 UTC, aprilspeight commented on Assets/Tutorials/BoundsControl/BoundsControl-LastPage.asset
> +          href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-spatialmanipulation/packages/spatialmanipulation/bounds-control\">Bounds
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:56 UTC, aprilspeight commented on Assets/Tutorials/CanvasButton/CanvasButton-10.asset
> +          href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/button\">Button</a>
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:56 UTC, aprilspeight commented on Assets/Tutorials/CanvasButton/CanvasButton-LastPage.asset
> +          \n\nBe sure to review our <a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/button\">Button</a>
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:56 UTC, aprilspeight commented on Assets/Tutorials/CanvasButton/CanvasButton-LastPage.asset
> +          and <a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcore/packages/uxcore/canvas-ui\">Volumetric
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:56 UTC, aprilspeight commented on Assets/Tutorials/CanvasButtonBar/CanvasButtonBar-6.asset
> +          you to refer to the <a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/button\">Button</a>
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:57 UTC, aprilspeight commented on Assets/Tutorials/CanvasButtonBar/CanvasButtonBar-LastPage.asset
> +          \n\nBe sure to review our <a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/button\">Button</a>
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:57 UTC, aprilspeight commented on Assets/Tutorials/CanvasButtonBar/CanvasButtonBar-LastPage.asset
> +          and <a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcore/packages/uxcore/canvas-ui\">Volumetric
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:57 UTC, aprilspeight commented on Assets/Tutorials/MRTKInputSimulation/MRTKInputSimulation-LastPage.asset
> +          our <a href="https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-input/packages/input/input-simulation">Input
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:57 UTC, aprilspeight commented on Assets/Tutorials/PreviewProject/PreviewProject-3.asset
> +          Follow our <a href="https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/preview-and-debug-your-app?tabs=openxr#set-up-holographic-remoting">Set
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:57 UTC, aprilspeight commented on Assets/Tutorials/PreviewProject/PreviewProject-4.asset
> +          for setup instructions.\n\n\u2022 <a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-getting-started\">Windows
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:57 UTC, aprilspeight commented on Assets/Tutorials/BoundsControl/BoundsControl-8.asset
> +          to the <a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-spatialmanipulation/packages/spatialmanipulation/bounds-control\">Bounds
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:57 UTC, aprilspeight commented on Assets/Tutorials/GettingStarted/GettingStarted-4.asset
> +          href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-project\">Initial
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:58 UTC, aprilspeight commented on Assets/Tutorials/ObjectManipulator/ObjectManipulator-9.asset
> +          has a collider component!\n\nWe encourage you to refer to the<a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-spatialmanipulation/packages/spatialmanipulat
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:58 UTC, aprilspeight commented on Assets/Tutorials/ObjectManipulator/ObjectManipulator-LastPage.asset
> +          needs. \n\nBe sure to review our <a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-spatialmanipulation/packages/spatialmanipulation/object-manipulator\">Obj
Please remove the locale code 'en-us' in the URL.

2023-07-26 22:58 UTC, aprilspeight commented on Assets/Tutorials/PreviewProject/PreviewProject-2.asset
> +          an <a href=\"https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-input/packages/input/input-simulation-quick-ref\">Input
Please remove the locale code 'en-us' in the URL.

2023-07-27 12:37 UTC, cheles commented on Packages/manifest.json
>      "com.microsoft.mrtk.uxcore": "file:MixedReality/com.microsoft.mrtk.uxcore-3.0.0-pre.11.tgz",
tested with MRTK3-prev17 and build/play works with no issues

2023-07-27 16:08 UTC, merged